# <u>Experiment - 06</u>

## To implement basic Unsupervised Neural Network learning rules for a problem.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# Generate synthetic data (for demonstration purposes)
num_samples = 1000
input_dim = 10

data = np.random.rand(num_samples, input_dim)

In [3]:
# Create an autoencoder model
encoder = keras.Sequential([
    layers.Input(shape=(input_dim,)),
    layers.Dense(5, activation='relu'),  # Encoder hidden layer with 5 neurons
])

decoder = keras.Sequential([
    layers.Input(shape=(5,)),  # Decoder input matches the number of neurons in the encoder's hidden layer
    layers.Dense(input_dim, activation='sigmoid'),  # Decoder output with sigmoid activation
])

autoencoder = keras.Sequential([encoder, decoder])

In [4]:
# Compile the autoencoder
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [5]:
# Train the autoencoder
autoencoder.fit(data, data, epochs=50, batch_size=32)

Epoch 1/50
32/32 [==============================] - 1s 2ms/step - loss: 0.0868
Epoch 2/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0852
Epoch 3/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0839
Epoch 4/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0825
Epoch 5/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0809
Epoch 6/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0790
Epoch 7/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0770
Epoch 8/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0750
Epoch 9/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0729
Epoch 10/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0707
Epoch 11/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0685
Epoch 12/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0665
Epoch 13/50
32/32 [==============================

In [6]:
# Use the trained encoder to encode data
encoded_data = encoder.predict(data)

32/32 [==============================] - 0s 1ms/step


In [7]:
# Check the reconstructed data
decoded_data = decoder.predict(encoded_data)

32/32 [==============================] - 0s 1ms/step


In [8]:
# Print the original and reconstructed data
print("Original Data:")
print(data[0])
print("Reconstructed Data:")
print(decoded_data[0])

Original Data:
[0.61316265 0.6007631  0.11179022 0.79887351 0.44498316 0.84531324
 0.67841774 0.74127428 0.96186875 0.75226275]
Reconstructed Data:
[0.511409   0.5268029  0.32712385 0.53812826 0.46671352 0.39162618
 0.6375007  0.78897184 0.52394795 0.58445084]


# Method - 2

In [1]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# Load and prepare data
iris = load_iris()
data = iris.data

scaler = StandardScaler() #standardize the data
scaled_data = scaler.fit_transform(data)
x_train, x_test = train_test_split(scaled_data, test_size=0.2, random_state=42)

input_dim = x_train.shape[1] #building the auto encoder

encoding_dim = input_dim  # Match encoding dimension to input feature count

In [3]:
encoder = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(input_dim,)),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.Dense(encoding_dim, activation = 'relu')
])

In [4]:
decoder = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(input_dim,)),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.Dense(encoding_dim, activation = 'sigmoid')
])

In [5]:
autoencoder = tf.keras.Sequential([encoder, decoder])

In [6]:
# compiling the model
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [7]:
# Training the model
autoencoder.fit(x_train, x_train, epochs=200, batch_size=16, shuffle=True)

Epoch 1/200
8/8 [==============================] - 1s 2ms/step - loss: 1.2618
Epoch 2/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2559
Epoch 3/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2510
Epoch 4/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2454
Epoch 5/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2405
Epoch 6/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2354
Epoch 7/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2301
Epoch 8/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2245
Epoch 9/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2184
Epoch 10/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2117
Epoch 11/200
8/8 [==============================] - 0s 1ms/step - loss: 1.2039
Epoch 12/200
8/8 [==============================] - 0s 1ms/step - loss: 1.1957
Epoch 13/200
8/8 [==============================] - 0s 1ms/st

8/8 [==============================] - 0s 1ms/step - loss: 0.6582
Epoch 105/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6571
Epoch 106/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6560
Epoch 107/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6551
Epoch 108/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6540
Epoch 109/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6530
Epoch 110/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6519
Epoch 111/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6508
Epoch 112/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6498
Epoch 113/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6484
Epoch 114/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6468
Epoch 115/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6443
Epoch 116/200
8/8 [==============================] - 0

In [9]:
# Evaluate the model
reconstructed_data = autoencoder.predict(x_test)

1/1 [==============================] - 0s 70ms/step


In [10]:
# Calculate the MSE betn original and reconstructed data
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(x_test, reconstructed_data)
print(f"Mean squared Error (MSE)is: {mse:.4f}")

Mean squared Error (MSE)is: 0.5421


In [11]:
print(reconstructed_data)

[[2.32412353e-01 2.19717142e-04 2.27083266e-01 1.07716911e-01]
 [7.56905283e-05 9.97419000e-01 3.42997396e-06 3.40520683e-06]
 [9.99972641e-01 6.91615154e-10 9.99515295e-01 9.96675193e-01]
 [1.27924189e-01 4.89741215e-05 4.12636757e-01 3.12715530e-01]
 [9.79015291e-01 1.16222276e-04 6.34754956e-01 2.29292601e-01]
 [2.70129967e-04 9.71311033e-01 3.88858098e-05 3.30444745e-05]
 [7.06065586e-03 8.10780097e-04 6.51279911e-02 5.32138944e-02]
 [9.90920067e-01 4.32169458e-07 9.90580618e-01 9.79023695e-01]
 [3.44070405e-01 1.82103392e-07 5.05993426e-01 2.46012554e-01]
 [2.91074961e-02 2.73743324e-04 7.86553174e-02 4.20084223e-02]
 [8.63436937e-01 6.39002610e-06 9.48804498e-01 9.24049675e-01]
 [6.29369752e-04 7.24296793e-02 8.90269992e-04 5.07951190e-04]
 [1.42062519e-04 9.95804727e-01 8.93226479e-06 8.61100216e-06]
 [4.84042161e-04 2.38351703e-01 3.99033510e-04 2.49263685e-04]
 [6.32296869e-05 9.97734070e-01 2.61714968e-06 2.61864011e-06]
 [5.66574395e-01 6.73266535e-04 6.32920563e-01 5.066120